package org.serratec.poo.classes;

public enum Cargo {
	GERENTE,
	SUPERVISOR,
	CONTABILIDADE,
	RECURSOS_HUMANOS,
	AUXILIAR_DE_SERVICOS_GERAIS,
	TECNICO_DE_MANUTECAO_DE_EQUIPAMENTO,
	PROFESSOR,
	ATENDENTE;
}
